<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="MongoDB.Bson" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\CorrespondenceCore.domain\CorrespondenceCore.domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CorrespondenceCore.domain">
      <HintPath>..\..\Domain\CorrespondenceCore.domain\bin\Debug\net8.0\CorrespondenceCore.domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
